# Predictive Fuel Planning for Flights

#### Keywords

fuel, airline, prediction

## A beginning.

Every airline is now a lower-cost airline. The worst financial crisis in the industry’s history over the last five years has forced all carriers to achieve cost efficiencies and higher productivity if they are to survive. 
  – Giovanni Bisignani – Director General & CEO, IATA
Per IATA’s latest fuel fact sheet, the global airline industry’s fuel bill is estimated to total $133 billion in 2016 (accounting for around 19% of operating expense at $44.6/barrel Brent of oil).
If we take Southwest Airlines - a typical major airline in U.S – as an example, the fuel cost in the first quarter of 2017 is $921,979,000 which makes up 22% of the operating expense or 19% of the total operating revenue of the airline. This mean that even 1% of fuel saving could potentially bring significant improvement on the airline’s financial status.
```{r machine-learning,echo=FALSE,fig.cap='[xkcd: Machine Learning](https://xkcd.com/1838/)',fig.align='center',out.width='50%'}
IATA Fuel Fact Sheet('https://www.iata.org/pressroom/facts_figures/fact_sheets/Documents/fact-sheet-fuel.pdf')
Southwest Report on First Quarter Profit('http://investors.southwest.com/news-and-events/news-releases/2017/04-27-2017-113101765g')
Fuel as a Percentage of Operating Expense from AviationDB('http://aviationdb.net/aviationdb/FuelExpenseByCarrierQuery#SUBMIT')
```

## A middle.

While fuel price is undoubtedly a primary driver of the fuel cost, the airlines don’t have much control over it. The part that the airline can improve is the process of planning and using fuel in a daily basis. One particular step of the process that has significant room for improvement is the flight planning during which the flight dispatcher use the flight planning system to decide how much that a flight is going to burn and how much fuel to add to the aircraft. Currently, the fuel planning calculation is based on theories from physics such as the head/tail wind model and prescribed cruise altitude. The actual historical fuel burn data which reflects other operational factors about fuel burn has not been taken into consideration during the fuel planning for future flights, these factors could be the risk of holding, delay, detour and traffic. Without such consideration, the current fuel plan will be subject to inaccuracy. The only measure the airline can take is to add extra fuel to every flight to compensate any possible additional fuel burn and such measure will significantly increase the overall fuel cost.

What we can do from the data science angle is to locate the primary driver of the fuel burn using historical flight data to see what kind of features affects the fuel burn and how much is that effect. For example, we may find out that the cruise condition – specifically the altitude and the wind – is one of the primary drivers of fuel burn. Then we may want to predict the cruise altitude and wind, but because the such information is not directly available before the flight when the flight dispatcher is making the fuel plan, we might need to also find the correlation between some pre-flight information that could potentially be translated to the condition during the flight. Another way to improve the accuracy of the fuel prediction is to use the similar historical flights to the upcoming flights as training dataset from prediction.

When the model is good enough, we could develop an application for flight dispatchers to review the predicted fuel burn when they are making the flight plan. This predicted value will influence the flight dispatchers’ fuel decision based on data and potentially help them add more accurate amount of fuel for the flights.


## An end.

The benefit of such analytics is multiple folders. First of all, the fuel prediction is not presented to the analysts in airline but directly to the flight dispatchers who make the fuel decision every day; second, the value is presented to them at the moment of decision making which has the greatest influence on the dispatchers on making fuel decisions; furthermore, such prediction is not generic but specifically target a flight which will make the analytic practical.

There are several challenges for such analytics. First, in order to reach a satisfactory level of accuracy, multiple data sources may need to be included, while some of them may be publicly available like weather, others may require private data from the airlines. Also, there may be obstacle from the regulation perspective since for many years the regulation has been requiring certain amount of extra fuel as part of the fuel planning process, the fuel prediction analysis may potentially lead the airline to deviate from that regulation even though such deviation is supported by data and analytics. However, regulation can be changed as long as the prediction is justified, and I believe using predictive analysis to do flight planning is only the matter of time.

